### ISSUE TITLE
Publications

### ISSUE THREAD

**Issue by Neobii** [copleykj/socialize-friendships#13]
I know that you have plans to take publications out of the packages.  However you should look at publish-composite, with the subscriptions you have, stuff with this is a breeze.

``` javascript
Meteor.publishComposite('friendConversation', function(friendUsername) {
    //check(friendUsername, String);
  return {
    find: function() {
        var user = Meteor.users.findOne(this.userId);
        var friend = Meteor.users.findOne({username: friendUsername});
        return Meteor.conversations.find({"_participants":{$in: [this.userId, friend._id]}});
    },
    children: [
    {
        find: function(convo){
            return convo.messages();
        }
    }
    ]
  }
});
```

**Comment by copleykj** [comment]
This is precisely why I wish to remove the publications from the packages. I happen to prefer one package for publications, however others my prefer any number of other packages. The plan is to remove them and provide examples of publications in the wiki's, possibly add on packages that are just the publications in case someone would like to just add them that way.
