### ISSUE TITLE
what if: meteor remove insecure autopublish

### ISSUE THREAD

**Issue by ericvrp** [copleykj/socialize-friendships#14]
When I remove the insecure and autopublish packages in Meteor 1.2.1 I see at most one (the current logged in) user with Meteor.users.find().fetch() in de browser' developer console .

What would need to be done to have socialize:friendships work safely without these two packages that are just for prototyping?

**Comment by copleykj** [comment]
You'll need to publish the necessary data. Since the data is normalized into separate collections, you will likely want to use one of the many "join" packages such as `tmeasday:publish-with-relations` or `reywood:publish-composite`. The wiki for this package has a publications page where you can find some examples of using the publish-with-relations package to publish the necessary data for most situations you will need.

**Comment by ericvrp** [comment]
Thank you for the quick reply!

I found the wiki and those publications work very well for me. The feature that IMHO is missing publishes user account information of people that the client searched for. Since only the current logged in user is available on the client I think it would be best to have a Server side method to handle the user-search by adding the found user._id to a list attached to the user account.

That way we can make sure that not all user id's and related info (username/email) will be published to all clients.

Alternatively the server should do the friendshipRequests.

Perhaps I am overlooking things so I would like to have your opinion on how to proceed with making your package more production ready.

**Comment by ericvrp** [comment]
This seems to take me a long way for now:

On the server...

```
Meteor.methods({

  GetUserId: function(username) {
    check(username, String);

    if (!this.userId) {
      throw new Meteor.Error(401, "You must be logged in!");
    }

    if (!Meteor.user().emails[0].verified) {
     throw new Meteor.Error(401, "You must be verified!");
    }

    var u = Meteor.users.findOne({username: username});

    if (!u) {
      throw new Meteor.Error(403, username + " does not exist!");
    }

    if (!u.emails[0].verified) {
     throw new Meteor.Error(401, username + " must be verified!");
    }

    // console.log("Server found " + username + " with id " + u._id);
    return u._id;
  }
});

Meteor.publish("UserInfo",
  function (userId) {
    check(userId, String);

    if(!this.userId) {  //this publish is only allowed for logged in users
        return this.ready();
    }

    return Meteor.users.find(userId, {fields: {username: 1}});
  }
);
```

On the client (PS I use React but I'm sure you get the goal here!)...

```
  _onInvite(event) {
    var username = this.refs.textInput.getValue().trim();
    // console.log("Invite " + username);
    Meteor.call('GetUserId', username, function(err, userId) {
      if (err) {
        console.log("Can't find " + username);
        return;
      }
      //console.log(username + " has userId " + userId);
      Meteor.subscribe("UserInfo", userId, {
          onReady() { Meteor.users.findOne(userId).requestFriendship(); }
        }
      );
    })
  },
```

**Comment by copleykj** [comment]
It looks to me like doing some unnecessary processing. In generally I would assume that if you are requesting a friendship the data would already be published to the client to display the user in a search result set, or for the users profile.

You'll have to forgive me as I've not taken the dive into React yet as I'm waiting for the more Meteorish patterns to emerge. 

So thinking in a blaze structure.. If you create a search page and add request functionality to it, you would likely iterate in an #each which would provide the context of the single user. Then in that context you can just call `this.requestFriendship();`.

``` javascript
Template.userSearchResult.events({
    'click .addFriend': function(){
        this.requestFriendship;
    }
});
```

Or a users profile...

``` html
<template name="userProfile">
    {{#with profileUser}}
        <!-- profile here -->
    {{/with}}
</template>
```

``` javascript
Template.userProfile.events({
    'click .addFriend': function(){
        this.requestFriendship;
    }
});
```

Like I said I'm not sure how you would accomplish this in React, but I'm sure its possible and this is the best possible pattern.

**Comment by ericvrp** [comment]
I seem to not make the core issue clear. It boils down to the fact that I can not do a requestFriendship before the user data is available on the client. But the user data is only available after a request has been made.

In my code it's only "var username = this.refs.textInput.getValue().trim();" that is really React specific. Let's ignore that detail. I think that if you use Blaze instead and remove autopublish the issue would be the same. (as far as I can see)

**Comment by copleykj** [comment]
Right.. So for every use case that I can imagine you would already have the data published to the client and then the data would be used to generate the interface that the user would interact with.

So for a search you would use the published data to display a list of found users.. Each of the results would have a corresponding data context of a user.. That context could then be used in an event like a click to just call the `requestFriendship` method

**Comment by ericvrp** [comment]
without autopublish you only have access to the current logged in user by default. The code above makes the user you search for available to the client.
