### ISSUE TITLE
Help making requests on the server

### ISSUE THREAD

**Issue by jerocosio** [copleykj/socialize-friendships#16]
Hi, so I want to use this package on my app, but for users to request friendship I don't want to publish all my users to the client, so I'm trying to make the request on the server, the think is that when I do it, a user can make many times the same request, something that isn't possible using the client, what could be wrong with my approach, here is what I'm trying to do:

somewhere-in-client.js

```
Meteor.call("buscarUsuario", emailUsuario, celularUsuario, function(error, result){
           if(error){
             swal({
               title: "Error",
               text: error.reason,
               type: "info",
               timer: 3000,
               showConfirmButton: false
            });
           }
           if(result){
             console.log('Este es el resultado');
             console.log(result);
           }
         });
```

somewhere-in-server.js

```
Meteor.methods({
  buscarUsuario: function (email,celular) {
    if(celular || email){
      var usuarioAmigo = Meteor.users.findOne(
        {$or:
          [
            {"emails.address": email},
            {"profile.celular": celular}
          ]
        }
      );
      if(usuarioAmigo){
        usuarioAmigo.requestFriendship();
        return usuarioAmigo;
      }else{
        throw new Meteor.Error("buscar-usuario-no-existe", "El usuario que estás buscando no existe.");
      }
    }else{
      throw new Meteor.Error("buscar-usuario-sin-info", "Esta información está incorrecta.");
    }
  }
});
```

I also tried returning the friend through the same method, but when I tried running 

```
if(result){
             result.requestFriendship
           }
```

I get an error, so I hope you can help me out with this, thanks in advance!

**Comment by copleykj** [comment]
The magic of the package is that everything is designed to be run from the client with all checks and balances in place to keep everything straight and from doing anything weird. You should not have to publish every user to the client, and most of the time I would imagine a friendship request being initiated from the users profile page and therefore the user would be published to the client already.

That being said, if for some reason you must call server methods then the relevant code which controls the request functionality is in the allow:insert check of the requests collection. https://github.com/copleykj/socialize-friendships/blob/master/request-model/server/server.js#L2-L21

**Comment by jerocosio** [comment]
Thanks, that snippet of code worked quite well with minor modifications. ;)
