### ISSUE TITLE
I think there's a little error on pendingRequests method

### ISSUE THREAD

**Issue by jerocosio** [copleykj/socialize-friendships#17]
The documentation says that the pendingRequests is 'a cursor of requests that the user has sent but have not been approved, denied or ignored.' but if you look at the actual method, just the requests that were not denied or ignored are the ones that get displayed.

```
pendingRequests: function (limit, skip) {
        var options = {limit:limit, skip:skip};
        return RequestsCollection.find({requesterId:this._id, denied:{$exists:false}, ignored:{$exists:false}}, options);
    }, 
```

**Comment by copleykj** [comment]
I think this is a documentation error as being denied or ignored would mean they have been responded to and therefore no longer pending.

**Comment by jerocosio** [comment]
Ok, I understand, is there anyway to display the denied requests, so that if a user wants to send a request again to that users it can erase the denied request and send one new.

**Comment by copleykj** [comment]
It was designed so that the requesting user wouldn't have that type of control so that they couldn't annoy other users by sending repeated requests to the same user. You can however control how many days the system requires between requests. See: https://github.com/copleykj/socialize-friendships#static-properties

Setting `User.restrictRequestDays` to 0 it should allow a user to immediately send another request after the previous one has been denied.

**Comment by steven-tib** [comment]
Hi @copleykj,

Thanks for this package, I'm using it successfully to add friends and deny them.
I'm facing problems when setting the `restrictRequestDays` to 0, it doesn't seem to allow me to do another request right after a deny. I wanted to simulate the "mistaken-deny click" from a user that actually wanted to validate the request. This user would then send another request right after but at the moment it's not possible. Understanding your last message this should be possible with `User.restrictRequestDays = 0`

I've set this parameter on the client-side on startup, and when checking from the console the value is effectively set at "0"

Anything I'm doing wrong? thanks for your help.

**Comment by copleykj** [comment]
>I've set this parameter **on the client-side on startup**, and when checking from the console the value is effectively set at "0"

You'll need to set this on the server as this being able to be set on the client would impede security.

**Comment by steven-tib** [comment]
!! works.. sorry I should have tried before on the server side. It makes sense about security issues.
Thank you for the fast reply.

**Comment by copleykj** [comment]
no problem, glad you got it working :)
