### ISSUE TITLE
insert a new "seen:false" field in the request Schema

### ISSUE THREAD

**Issue by kaiyes** [copleykj/socialize-friendships#19]
Hi, 
I am trying to insert a new "seen:false" field in the request Schema. I know there are ways to locally edit packages , I am not after that info. What I am asking is whether adding a `seen:false` for notification and and using a click event to set it to `seen:true` is proper way to achieve the notification ? I only need to feed a `cursor.count()` to a template. 

Currently I am trying  like this 
![screen shot 2016-02-13 at 11 39 43 am](https://cloud.githubusercontent.com/assets/5293742/13026110/86645204-d246-11e5-8453-be7e27d8619e.png)

**Comment by copleykj** [comment]
You could do it this way if that is what you are trying to achieve. I'd probably get rid of the `autoValue` as I don't see a need since the same is achieved with the `defauleValue` in this case.

Personally as far as friend requests go I display a count for all of the notifications that haven't been either denied or ignored. This means the user has to specifically address each request though so it may not be what you are going for and in which case you'll want to add the extra key and update it accordingly.

**Comment by kaiyes** [comment]
Thanks for answering !! I have been using the friend request methods to show notification of requests sent and its working great along with a notification badge package. But I need one for chat.  I should have posted it in `socialize-messaging` package's issue.

**Comment by copleykj** [comment]
Oh!! So the messaging package is set up with a "read" key on the participant record for the user that is participating in a conversation, so finding all of the participant records where document.userId == Meteor.userId() will give you all the conversations that have not been read by the current user..

The `viewingConversation` publication is best used as well. Subscribing to this publication when the conversation is viewed will set the read key on the participant record to true and the fact that the user is observing the conversation will be recorded. This will in turn keep the read key from being set back to false while the user is currently viewing the conversation. When the user stops viewing the conversation (navigates away, or conversation component is destroyed/unmounted) you can stop the subscription and the fact that the user is no longer observing the conversation will be noted and this will allow the read key to be set back to false when new messages come in. Also this still works if the user is viewing the conversation from multiple browser tabs and the user will be considered observing the conversation until the user navigates away from the conversation in all tabs/browsers.
