### ISSUE TITLE
Publication of friends

### ISSUE THREAD

**Issue by paulgration** [copleykj/socialize-friendships#2]
When subscribing to the friends publication with `Meteor.subscribe('friends');` and trying to access the friends of a user by calling `Meteor.user().friends().fetch()` in a browser console I was getting an empty array result - despite there being a friendship existing for the user in the friends collection.
Looking into the publication (friend-model/server/publication.js) it uses SimplePublication and the selector has document properties that match the schema of the friends collection but the options property is given a value which is set here: `options.fields = {username:1, createdAt:1, "profile.online":1, "profile.tagline":1, "profile.photo":1};`. My understanding of mongo is that this is to force the result to return only those properties (fields) in the result, but they look like properties of a user document rather than friend document.
When removing that line, the friend publication works and the aforementioned fetch of user friends works as expected - I don't fully understand the simple publication package yet but wondered if this is a line that shouldn't be there or if I'm doing something else wrong here?

**Comment by copleykj** [comment]
Yes, very sorry.. I dissected this package out of another project so it could be open sourced and that appears to be some remnants of the other project that I missed. I've removed it and it should be set to go now.
