### ISSUE TITLE
Problems displaying requests in React

### ISSUE THREAD

**Issue by matwii** [copleykj/socialize-friendships#22]
Currently im just testing this package with sending a friendrequest like this:
`askFriend(email){
        var user = Accounts.findUserByEmail(email);
        user.requestFriendship();
    }`

and displaying the number of requests like this:
`console.log('this.user: ', Meteor.user().numRequests());`
But I am just getting up 0 whatever I do.

**Comment by StorytellerCZ** [comment]
You need to properly subscribe to all the data. In short you are missing certain data pieces on your client.

Here is a sample of how you should publish: https://github.com/StorytellerCZ/Socialize-starter/blob/master/server/publications/friendships.js#L55

Note that I'm using publish composite which is a third-party package to publish all the related documents together.

**Comment by matwii** [comment]
Okay thanks, but where in your code are you subscribing on this collection in the client? I'm having a bit trouble understanding it cause im using Tracker.React.

**Comment by StorytellerCZ** [comment]
I'm using Mantra, so I subscribe in container for the react component.

https://github.com/StorytellerCZ/Socialize-starter/blob/master/client/modules/users/containers/dashboard_friends.js

**Comment by matwii** [comment]
I am getting an error when I'm trying to run the project that says: 
.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

**Comment by matwii** [comment]
Okay thanks! One last question, where are you sending the props that you
are using in your FriendRequest component from ?

2016-10-20 22:13 GMT+02:00 Jan Dvorak notifications@github.com:

**Comment by StorytellerCZ** [comment]
Not sure what you mean, I only have one prop, which is the list of requests which comes from container of the same name (go into the container file in that module to see them).
