### ISSUE TITLE
request.requester() won't work if I refresh the page.

### ISSUE THREAD

**Issue by matwii** [copleykj/socialize-friendships#23]
So I have a problem where I subscribe to the request collection and I am getting all the data I need if I just click on the link etc. But if I am in my friend page and refresh the page with F5 I will get all my requests, then after I map through them it will stop at request.requester(). How can I solve this problem ?

**Comment by copleykj** [comment]
I'm not sure I can diagnose the issue with so little information. Do you have a repo or a reproduction I can look at to try to figure it out?

**Comment by copleykj** [comment]
Closing this for now. Feel free to open it back up if you have a way that I can reproduce this.
