### ISSUE TITLE
TypeError: user is null  meteor.js:930:11 .hasRequestFrom@http://localhost:3000/packages Socialize friendship meteor

### ISSUE THREAD

**Issue by varunajmera0** [copleykj/socialize-friendships#24]
![image](https://cloud.githubusercontent.com/assets/22893376/23091411/54b5cada-f5db-11e6-905c-ef4093b36d59.png)

some time it gives in chrome also, but it always gives in mozilla whenever i refresh.

whenever i refresh browser, it gives an error hasRequestFrom ._id is null.
Exception from Tracker recompute function:  meteor.js:930:11
Error: No such function: hasRequestFrom

Exception from Tracker recompute function:  meteor.js:930:11
TypeError: user is null  meteor.js:930:11
.isFriendsWith@http://localhost:3000/packages

Exception from Tracker recompute function:  meteor.js:930:11
TypeError: user is null  meteor.js:930:11
.hasRequestFrom@http://localhost:3000/packages

**Comment by copleykj** [comment]
So this error is pretty self explanatory.. You have called `hasRequestFrom(user)` with the user prop having the value of null. Just pass in a user to check against.

For future reference, file an issue and be patient. Don't file an issue, then post the issue on Google+ and THEN also post the issue to a comment on my YouTube channel.

**Comment by varunajmera0** [comment]
{{#if currentUser.hasRequestFrom  this}} 
        
         <div class="btn btn-primary accept">Accept friend request</div>
         {{else}}
             {{#if hasRequestFrom currentUser}}
            <div class="btn btn-primary cancel-request" >cancel-friendship</div>
            {{else}}
            <button class="btn btn-primary add-friend">Add Friend</button>
    
            {{/if}}
        {{/if}}
i did . like mentioned in doc i followed same. but when u refresh the browser {{#if currentUser.hasRequestFrom  this}}  , this will flush ......or "hasRequestFrom(user) with the user prop having the value of null" - you said but whenever u will refresh browser user /this will flush . i am saying this that this is not working properly. @copleykj

**Comment by varunajmera0** [comment]
{{#if currentUser.isFriendsWith this}}
        <div class="btn btn-primary end-friendship" >Unfriend</div>
           
     {{else}}
     
       {{#if currentUser.hasRequestFrom  this}} 
        
         <div class="btn btn-primary accept">Accept friend request</div>
         {{else}}
             {{#if hasRequestFrom currentUser}}
            <div class="btn btn-primary cancel-request" >cancel-friendship</div>
            {{else}}
            <button class="btn btn-primary add-friend">Add Friend</button>
    
            {{/if}}
        {{/if}}
       
  {{/if}}
        here is my code but whenever u refresh this will flush and In mozilla browser it happens every time. and sometime in Chrome also. @copleykj

**Comment by copleykj** [comment]
That's because your data isn't ready. You need to wait for your subscriptions to be ready before you render that part of your template.

**Comment by varunajmera0** [comment]
i dont get it.  i have to make pub and sub function for this. "That's because your data isn't ready. You need to wait for your subscriptions to be ready before you render that part of your template.". can u explain little bit more. actually i am newbie. @copleykj  
or u r saying on router wait on i have to put?

**Comment by copleykj** [comment]
What ever you have to do to make this part of the template not render until you have the user record for the user you pass to `hasRequestFrom`. If you are subscribing to your data as needed (which you should be) then you can use the ready function of the object returned from the subscribe call. If not you could create a helper that returns the result of `DDP._allSubscriptionsReady()`

As far as waitOn in the router, I'd seriously avoid it in favor of template level subscriptions. Personally I'd move away from Iron Router as well but that's another whole issue in itself.

**Comment by varunajmera0** [comment]
Router.route('/users/:username', {
    name: 'userProfile',
    waitOn: function(){
        Meteor.subscribe('friendRequests');
    },
    data: function(){
       
           return Meteor.users.findOne({username: this.params.username});
      
    }
});


https://github.com/copleykj/socialize-friendships/wiki/Publications
can i use this which is provided by you. 
i am calling wait on  and i will make publish this. @copleykj

**Comment by copleykj** [comment]
That should basically work, but if I recall correctly you need to return the subscription result from waitOn

**Comment by varunajmera0** [comment]
can u give example i am confused? @copleykj

**Comment by copleykj** [comment]
```javascript
Router.route('/users/:username', {
    name: 'userProfile',
    waitOn: function(){
        return  Meteor.subscribe('friendRequests');
    },
    data: function(){
        return Meteor.users.findOne({username: this.params.username});
    }
});
```

**Comment by varunajmera0** [comment]
thanks alot bro.  :) @copleykj

**Comment by copleykj** [comment]
No problem.

**Comment by varunajmera0** [comment]
bro i am making lib/collection.js . in this i am putting this code 
https://github.com/copleykj/socialize-friendships/wiki/Publications.
 and wait on router side  i am returning this  return  Meteor.subscribe('friendRequests');
This is right ? @copleykj

**Comment by varunajmera0** [comment]
this code should right on server side or client side

**Comment by varunajmera0** [comment]
this is not working publish code how should write. it is showing Loading... only @copleykj

**Comment by copleykj** [comment]
Sorry man, this isn't something I can debug on my end.

**Comment by varunajmera0** [comment]
Package name socialize messaging
this is js part
conversation.messages(/*optional params*/).forEach(function(message){
	console.log(message.user().username, ": ", message.body);
});
 this is template part
{{#each messages}}
	{{message.user.username}}: {{message.body}}
{{/each}}
but messages how will get messages. here is no  conversation link with message. it will work directly without conversation.?? @copleykj
