### ISSUE TITLE
Examples on how to use socialize-friendships

### ISSUE THREAD

**Issue by SantoshSrinivas79** [copleykj/socialize-friendships#4]
Thanks for the package. I am trying to understand how to use the functionality and wondering if you could provide some direction.

Could you please provide some examples on how to use e.g. how to send a friend request, how to check if a user is a friend, etc? Something on the lines of [Azeirah/meteor-friends](https://github.com/Azeirah/meteor-friends) but with sample code?

**Comment by stefvw** [comment]
Example code would be much appreciated indeed! Eager to test out the package, but can't make up much from the repo readme...

**Comment by jerocosio** [comment]
+1, I think it would be great to add some demo or explain in more detail how to use this friendship package. ;)

**Comment by pcuci** [comment]
+1, happy to experiment as well

**Comment by copleykj** [comment]
Working on this, just have a very limited amount of time currently.

**Comment by sireskay** [comment]
+1

**Comment by copleykj** [comment]
Live 10PM https://www.youtube.com/watch?v=ENPVrGmod28

**Comment by sireskay** [comment]
@copleykj excellent work mate!

**Comment by copleykj** [comment]
I've just reworked the documentation a bit to make things more clear. Any feedback would be much appreciated.

**Comment by ghost** [comment]
Thanks @copleykj ! The documentation looks very good. Could you update the package on atmospherejs.com so I can try it out?

**Comment by copleykj** [comment]
0.4.0 just published

**Comment by ghost** [comment]
Great :)

**Comment by copleykj** [comment]
Now that documentation ins't so lacking I'm closing this. If it is not sufficient please feel free to reopen.

**Comment by ghost** [comment]
Under "Instance Methods", I think 
`<p>{{user.username}} would like to be friends</p>`
should be
`<p>{{requester.username}} would like to be friends</p>`

**Comment by copleykj** [comment]
Awesome, thanks.

**Comment by jerocosio** [comment]
I also had to change this:

```
Template.userProfile.events({
    'click [data-action=accept]': function() {
        //assumes context is a instance of a user
        this.acceptFriendshipRequest();
    }
});
```

to this, and I suspect all the instance methods need this change:

```
Template.contenidoSolicitudAmigosVyno.events({
    'click [data-action=accept]': function() {
        //assumes context is a instance of a user
        this.accept();
    }
});
```

**Comment by copleykj** [comment]
@cosio55 You would use this.accept(); if the context was a request instance, and this.acceptFriendRequest() if the context as a user who had sent the currently logged in user a request.

**Comment by steven-tib** [comment]
Hi @copleykj, I'm adding this package to my app right now, and so far it seems to work (after a bit of trouble trying to set it up). Just wanted to mention that the video from this post helped me a lot so, should you maybe add it to the documentation ? 
Thanks a lot for your work! cheers
