### ISSUE TITLE
Request object state

### ISSUE THREAD

**Issue by Joe312341** [copleykj/socialize-friendships#5]
Hello,

 I feel like there has to be an active / inactive attribute for the request object.

When I accept a request I do not want to remove it because that just allows me to send a request again.
But once I am friends I also do not want to show that request anymore.

Regards,
Joe

**Comment by copleykj** [comment]
I have a fix for this in the works.. Should be able to get it out by tonight.

**Comment by Joe312341** [comment]
Hey, just saw the change. Thank you!

**Comment by copleykj** [comment]
You're very welcome..
