### ISSUE TITLE
Iron-router to Flow-router

### ISSUE THREAD

**Issue by sireskay** [copleykj/socialize-friendships#6]
Thanks @copleykj for all your hard work. I am wondering will it be possible for all the sociallize package be updated to Flow-router? Iron-router seems to not be continuous development and maintenance as well as flow-router!

**Comment by copleykj** [comment]
All of the socialize packages are router agnostic.

**Comment by sireskay** [comment]
Aweson thanks. I will try it with flow-router then.Any update on an examplet of one of the packages? please please!
