### ISSUE TITLE
Access denied when trying to send a requestFriendship()

### ISSUE THREAD

**Issue by jerocosio** [copleykj/socialize-friendships#8]
Hi, I am trying to send a friend request like this:

```
Meteor.users.findOne({_id:"ACTUAL USER ID"}).requestFriendship()
```

But I'm getting the error `insert failed: Access denied` I think this has something to do with the fact that the model 'Request' doesn't has the allow method on the server to add it, as I looked in the package I think you should add it the same way `RequestsCollection` has it. Or do you have any other suggestion?

**Comment by copleykj** [comment]
lines [7-13 of request-model/server/server.js](https://github.com/copleykj/socialize-friendships/blob/master/request-model/server/server.js#L7-L13) controls request insertion.

Simply put these line state that
1. The user making the request must not be the same as the user they are making a request (self friendship) or already friends with the user.
2. The users can't be blocking the requester or vise versa.
3. A request can't already exist from the requester to the user or vise versa.

As long as all of these checks pass the request should go through properly. If you are getting access denied then one of these is failing. I'll see about adding some better errors in the next release, but until then my best guess would be to check if a request exists between the 2 users.

**Comment by copleykj** [comment]
The 0.4.0 release should give some better errors now.
